### ISSUE TITLE
Changing HDMI output not working

### ISSUE THREAD

**Issue by EinarHolm69** [RonnyWinkler/homey.sonybraviaandroidtv#1]
The HDMI ís empty

Here are dianostics info 

35f8687d-c8e4-4f51-947b-62dbeae62588

**Comment by RonnyWinkler** [comment]
Your device is not reacheable: Error: connect ECONNREFUSED 192.168.1.88:80
Has the IP changed? Please set a fixed IP in DHCP settings of your router.

**Comment by EinarHolm69** [comment]
Thanks

Working

Kveðja, Einar
S. 5178111


On 2 Sep 2024, at 21:07, Ronny Winkler ***@***.***> wrote:

﻿

Your device is not reacheable: Error: connect ECONNREFUSED 192.168.1.88:80
Has the IP changed? Please set a fixed IP in DHCP settings of your router.
