### ISSUE TITLE
Flowcard When Inactivated and Activated do not work

### ISSUE THREAD

**Issue by cube65** [RonnyWinkler/homey.sonybraviaandroidtv#3]
Hi!

Thankyou for a great app.

I am Using "When" for the TV being activated and inactivated in a Homey Advanced Flow, and it do not trigger/work when I am using the remote to turn the TV on or off.

However if I turn the TV on or off using your app in Homey, it triggers just fine, and it is possible to control the TV from a Homey flow.

Is the When for TV being activated or not activated supposed to work when using the remote control also?

Kind regards
Urban

**Comment by RonnyWinkler** [comment]
Hi, the app is polling the TVs state. The Homey device state should change with the next data reading. You can decrease the polling interval im device settings if you need faster response.
Kind regards
Ronny

**Comment by cube65** [comment]
Hi again!

Thankyou for the quick response.

I looked in the settings before posting the Issue, I should have connected the dots that the app is polling :)

However, I set it to 15 seconds, and it works. I have no real sense how much it increases the load on my Homey, but hopefylly it will be OK.

Merry Christmas and thankyou.

/Urban
